export const ERROR_MESSAGES = {
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
  INVALID_NEW_PASSWORD: "INVALID_NEW_PASSWORD",
  PASSWORDS_DO_NOT_MATCH: "PASSWORDS_DO_NOT_MATCH",
  EMAIL_ALREADY_USED: "EMAIL_ALREADY_USED",
  NO_FILE_UPLOADED: "NO_FILE_UPLOADED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  IMAGE_PROCESSING_ERROR: "IMAGE_PROCESSING_ERROR",
  UPLOAD_FAILED: "UPLOAD_FAILED",
};
